# 设备选择
device: cpu  # 可以是 'cuda' 或 'cpu'
#gpus: [0, 1]  # 指定要使用的GPU ID列表, 如果device是'cuda'

# 环境设置
env_name: BreakoutNoFrameskip-v4

# Rainbow DQN 特定参数
atom_size: 51
v_min: -10
v_max: 10

# 训练参数
batch_size: 124
gamma: 0.99
eps_start: 1.0
eps_end: 0.01
eps_decay: 1000000
target_update: 10000
num_steps: 5000000
memory_size: 100000 
policy_update: 4
evaluate_freq: 250000
lr: 0.0000625
adam_eps: 1.5e-4
gradient_accumulation_steps: 8  

# 评估参数
evaluate_eps: 0.05
evaluate_num_episodes: 20
evaluate_freq: 10000
evaluate_episodes: 10

# 课程学习参数
curriculum_thresholds: [50, 100, 150]

# 其他设置
seed: 42
save_dir: checkpoints
save_frequency: 1000000
log_dir: logs
inference_model_path: 'checkpoints/BreakoutNoFrameskip-v4_best_model.pth'

use_mixed_precision: true
learning_rate_decay: 0.99

# 优先经验回放参数
prioritized_replay_alpha: 0.6
prioritized_replay_beta: 0.4
prioritized_replay_beta_frames: 100000