# 设备选择
device: cuda  # 可以是 'cuda' 或 'cpu'
gpus: [0, 1]  # 指定要使用的GPU ID列表, 如果device是'cuda'

# 其他设置保持不变
env_name: Breakout
batch_size: 32
gamma: 0.99
eps_start: 1.0
eps_end: 0.01
eps_decay: 1000000
target_update: 10000
num_steps: 5000000
memory_size: 100000 
policy_update: 4
evaluate_freq: 250000
lr: 0.0000625
adam_eps: 1.0e-8

evaluate_eps: 0.05
evaluate_num_episodes: 20
evaluate_freq: 10000
evaluate_episodes: 10

seed: 42
save_dir: checkpoints
save_frequency: 1000000
log_dir: logs
inference_model_path: 'checkpoints\Breakout_final_model.pth'

use_mixed_precision: true
learning_rate_decay: 0.99
prioritized_replay_alpha: 0.6
prioritized_replay_beta: 0.4
prioritized_replay_beta_frames: 100000